name: Docker

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: zbeekman/ShellCheck-Linter-Action@v1.0.1
      - name: Install Dependencies
        run: make install
      # - name: Build
      #   run: ./scripts/build.sh
      - name: Test
        run: make test

  # https://www.prestonlamb.com/blog/creating-a-docker-image-with-github-actions
  publish:
    name: Publish-x86
    needs: [build]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/v[0-9]+'))
    runs-on: ubuntu-latest
    env:
      TARGET: x86
      SUBTARGET: 64
      PLATFORM: x86_64
      ARCH: linux/amd64
      CLASH_ARCH: amd64
      IMAGE_TAG: x86_64
      TZ: Asia/Shanghai

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Login To DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PWD }}

    - name: Build & Push Multiarch Image
      uses: docker/build-push-action@v2
      with:
        platforms: ${{ env.ARCH_64 }}
        file: Dockerfile
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/wine:${{ env.IMAGE_TAG }}
